version: '3'
services:
  jenkins:
    container_name: jenkins
    build:
      context: .
    ports:
    - 8000:8080
    - 4040:4040
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - jenkins-vol:/var/lib/jenkins

volumes:
  jenkins-vol: